---
title: "R Notebook"
output: html_notebook
---


```{r}
library(VGAM)
library(tidyverse)
```

BOBYQA

```{r}
red <- read_csv("../data/training_data/red_train.csv")
```

```{r}
complete_red <- red %>% drop_na() %>% 
  mutate(quality_f = as.factor(quality))
```


```{r}
source("../R/multinomial_likelihood.R")
```


```{r}
source("../R/multinomial_likelihood.R")
set.seed(13)
l <- data_to_mulitnomial(complete_red, formula(quality ~ alcohol + `volatile acidity` + `total sulfur dioxide` + pH + sulphates), ref_level = "8")
y <- l[[1]]
X <- l[[2]]
b_vector <- matrix(rnorm(runif(ncol(y)*ncol(X),-2,2)), byrow = T, nrow = ncol(X)*ncol(y), ncol = 1)
multinomial_log_likelihood(y,X,b_vector)
```

```{r}
library(optimx)

fit <- optimx(
  par = c(b_vector),
  fn = function(x, y, X){multinomial_log_likelihood(y = y,
                                                    X = X,
                                                    b_vector = x)},
  # gr = function(x, y, X){mll_gradient(y = y,
  #                                     X = X,
  #                                     b_vector = x)},
  y = y,
  X = X,
  method =  "BFGS",
  hessian = F,
  control = list(
    trace = 1,
    abstol = 10e-7,
    maximize = T
  )
)
```

```{r}


x <- coef(vglm(quality ~ 1 + alcohol + `volatile acidity` + `total sulfur dioxide` + pH + sulphates, data = complete_red,family= multinomial(refLevel = "8"))) 

%>% 
  matrix(ncol = ncol(X)) %>% 
  t() %>% 
  matrix(ncol = 1)

abs(x - fit[1:30]) %>% 
  as.matrix() %>% mean()

```



